export const MOCK_TARIFFS = [
  {
    id: 'mock-starter',
    code: 'STARTER',
    name: 'Старт',
    description: 'Пакет для небольших разовых подборок документов.',
    price: 0,
    currency: 'RUB',
    durationDays: 30,
    dailyTokenLimit: 50_000,
    sectionScope: 'ALL' as const,
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 'mock-pro',
    code: 'PRO',
    name: 'Профессиональный',
    description: 'Рабочий режим для регулярной подготовки судебных пакетов.',
    price: 0,
    currency: 'RUB',
    durationDays: 30,
    dailyTokenLimit: 250_000,
    sectionScope: 'ALL' as const,
    isActive: true,
    sortOrder: 20,
  },
  {
    id: 'mock-team',
    code: 'TEAM',
    name: 'Команда',
    description: 'Мок-тариф для будущего биллинга и командной работы.',
    price: 0,
    currency: 'RUB',
    durationDays: 30,
    dailyTokenLimit: null,
    sectionScope: 'ALL' as const,
    isActive: true,
    sortOrder: 30,
  },
];

export const MOCK_TOKEN_PACKAGES = [
  {
    id: 'mock-100k',
    code: 'TOKENS_100K',
    name: '100 тысяч токенов',
    description: 'Тестовый пакет для проверки механики пополнений.',
    tokenAmount: 100_000,
    price: 0,
    currency: 'RUB',
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 'mock-500k',
    code: 'TOKENS_500K',
    name: '500 тысяч токенов',
    description: 'Мок-пакет для больших загрузок и OCR.',
    tokenAmount: 500_000,
    price: 0,
    currency: 'RUB',
    isActive: true,
    sortOrder: 20,
  },
  {
    id: 'mock-2m',
    code: 'TOKENS_2M',
    name: '2 миллиона токенов',
    description: 'Резервный пакет для нагрузочных проверок.',
    tokenAmount: 2_000_000,
    price: 0,
    currency: 'RUB',
    isActive: true,
    sortOrder: 30,
  },
];
